### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by ryantpayton** [flwmxd/WzTools#2]
I can't seem to find any of the includes for Others

ex. `#include "../Others/Console.h"`

**Comment by flwmxd** [comment]
console is a log library.  you can remove or replace it

**Comment by ryantpayton** [comment]
I removed console but the StringUtils was hard to find. I found a library but reading anything past the parent node came in blank. If you look at the children in one of the parent nodes all the names are a mess of characters.

**Comment by flwmxd** [comment]
In fact, StringUtils is used to convert string from utf8 to utf16 in my project.  I try to use codecvt, but there are some bugs in this library. So I write a library for coverting.  I will update this project after serveal days.

**Comment by flwmxd** [comment]
Besides, if you want to use this library to read GMS or KMS client you should deduce these client AES key, the current key only used in CMS client. To read the more details about AES key, you can see NoLifeStory. (I'm lazy......)

**Comment by ryantpayton** [comment]
No that helps a lot thank you. I think I know how to adjust from here. 謝謝

**Comment by flwmxd** [comment]
@ryantpayton  I have update this project and it can be single compiled.

**Comment by ryantpayton** [comment]
Thank you very much!
